instOpcode(0x88, 4)
instCode(r_A = r_A + r_B)
instEnd()
instOpcode(0x89, 4)
instCode(r_A = r_A + r_C)
instEnd()
instOpcode(0x8A, 4)
instCode(r_A = r_A + r_D)
instEnd()
instOpcode(0x8B, 4)
instCode(r_A = r_A + r_E)
instEnd()
instOpcode(0x8C, 4)
instCode(r_A = r_A + r_H)
instEnd()
instOpcode(0x8D, 4)
instCode(r_A = r_A + r_L)
instEnd()
/*
instOpcode(0x8E, 4)
instCode(r_A = r_A + r_HL)
instEnd()
 */
instOpcode(0x8F, 4)
instCode(r_A = r_A + r_A)
instEnd()
